### ISSUE TITLE
Can't generate result on Windows 10

### ISSUE THREAD

**Issue by fahim9778** [hjalti/mossum#9]
I am trying to generate mossum results on a Windows 10 PC. but if I run the following command on Powershell 

`PS C:\Users\User> mossum http://moss.stanford.edu/results/x/xxxxxxxxx/`

it shows nothing, rather the `mossum.py` opens in VS Code.

I have also tried with CMD, but CMD doesn't recognize `mossum ` as a command. I have `Graphviz` installed on my PC.

**Comment by wanjizheng** [comment]
any solutions?

**Comment by fahim9778** [comment]
@wanjizheng No, not yet. :(

**Comment by fahim9778** [comment]
@hjalti Dear author, would you please look into this problem?

**Comment by hjalti** [comment]
Hi, sorry for the very late reply. Unfortunately both my Windows and teaching days are behind me now, so it's hard for me to try to reproduce this issue. However, it sounds like Windows is not associating mossum with Python or that the directory in which PIP installs binaries is not in your path. 

You can try cloning or downloading the repository directly, opening the `mossum` directory in CMD or PowerShell and running `python mossum.py -h`. If Python is correctly set up, then you should see some output (or an error regarding missing dependencies). If dependencies are missing you can install them using PIP.

```
python -m pip install --user "beautifulsoup4>=4.3.2" "Faker>=0.4.2" "html5lib>=0.999" "ipython>=2.3.0" "pydot>=1.0.29" "pyparsing>=2.0.2" "requests>=2.4.3" "six>=1.8.0" "pydot>=1.2.4"
```

Instead of running `mossum` you should then be able to run `python mossum.py` in the repository's `mossum` directory in the same manner.

**Comment by fahim9778** [comment]
@hjalti Thank for for your answer. I tried your solution, but this time when I pass the URLs using `python mossum.py  http://moss.stanford.edu/results/x/xxxxxxxxx/ http://moss.stanford.edu/results/x/yyyyyyyyy/`, now it shows the following errors
`File "C:\Users\User\AppData\Local\Programs\Python\Python39\Lib\site-packages\mossum\mossum.py", line 301, in <module>
    main()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\Lib\site-packages\mossum\mossum.py", line 282, in main
    res = get_results(x)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\Lib\site-packages\mossum\mossum.py", line 220, in get_results
    for row in soup.table('tr')[1:]:
TypeError: 'NoneType' object is not callable`

Can you please look into this? I am attaching a screenshot for the reference.
![image](https://user-images.githubusercontent.com/26436023/147582577-22cc3fc9-be98-4d11-9233-db7ea3a10e01.png)

**Comment by Bogay** [comment]
@fahim9778
The URL you pass to `mossum` might be wrong. You should give `http://moss.stanford.edu/results/x/xxxxxxxxx/` instead of `http://moss.stanford.edu/results/x/xxxxxxxxx/matchxxx.html`. The `matchxxx.html` part should be removed.
I can get the same error message if I use the latter URL, but the former one works properly.

**Comment by fahim9778** [comment]
@Bogay Thank you for your reply. I already got it via emailing the author @hjalti . He was super helpful.
Thank you too for posting the solution. I kinda forgot to add the fix.
